version: "3.8"

services:
  db:
    container_name: gopher-chat-db
    image: postgres:12.4-alpine
    volumes:
      - "./database/gopher-chat-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: gopher-chat
    ports:
      - "5432:5432"
    restart:
      unless-stopped
      