basePath: /v1
definitions:
  github_com_LikhithMar14_gopher-chat_internal_models.Comment:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      post_id:
        type: integer
      updated_at:
        type: string
      user:
        $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.User'
      user_id:
        type: integer
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.CreateCommentRequest:
    properties:
      content:
        maxLength: 500
        minLength: 1
        type: string
    required:
    - content
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.CreatePostRequest:
    properties:
      content:
        maxLength: 1000
        minLength: 10
        type: string
      tags:
        items:
          type: string
        maxItems: 5
        minItems: 1
        type: array
      title:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - content
    - tags
    - title
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.FeedItem:
    properties:
      author:
        $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.User'
      post:
        $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.Post'
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.FeedResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.FeedItem'
        type: array
      pagination:
        $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.PaginationInfo'
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.PaginationInfo:
    properties:
      current_page:
        type: integer
      has_next:
        type: boolean
      has_previous:
        type: boolean
      items_per_page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.Post:
    properties:
      comments:
        items:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.Comment'
        type: array
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      version:
        type: integer
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.RegisterUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.UpdatePostRequest:
    properties:
      content:
        maxLength: 1000
        type: string
      tags:
        items:
          type: string
        maxItems: 5
        type: array
      title:
        maxLength: 100
        type: string
    type: object
  github_com_LikhithMar14_gopher-chat_internal_models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse:
    properties:
      data: {}
      error:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Gopher Chat API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gopher Chat API
  version: 1.0.0
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided information
      parameters:
      - description: User registration details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      summary: Registers a user
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: Get the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: Health check successful
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      summary: Health check
      tags:
      - health
  /posts:
    post:
      consumes:
      - application/json
      description: Create a new post with title, content, and tags
      parameters:
      - description: Post creation request
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Post created successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a new post
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a post by its ID
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Post deleted successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: Post not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete a post
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: Retrieve a specific post by its ID, including comments
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Post retrieved successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: Post not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      summary: Get post by ID
      tags:
      - posts
    patch:
      consumes:
      - application/json
      description: Update an existing post's title, content, or tags
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Post update request
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Post updated successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: Post not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "409":
          description: Version conflict
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Update a post
      tags:
      - posts
  /posts/{id}/comments:
    get:
      consumes:
      - application/json
      description: Retrieve all comments for a specific post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Comments retrieved successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: Post not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      summary: Get comments for a post
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: Add a new comment to a specific post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Comment creation request
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.CreateCommentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Comment created successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: Post not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a comment on a post
      tags:
      - comments
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all users in the system
      produces:
      - application/json
      responses:
        "200":
          description: success response with users array and count
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided information
      parameters:
      - description: User creation request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Get user by ID
      tags:
      - users
  /users/{id}/follow:
    delete:
      consumes:
      - application/json
      description: Unfollow a user to stop seeing their posts in your feed
      parameters:
      - description: User ID to unfollow
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User unfollowed successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Unfollow a user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Follow another user to see their posts in your feed
      parameters:
      - description: User ID to follow
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User followed successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Follow a user
      tags:
      - users
  /users/me/feed:
    get:
      consumes:
      - application/json
      description: Retrieve a paginated feed of posts from followed users
      parameters:
      - description: 'Page number (default: 1)'
        in: query
        name: page
        type: integer
      - description: 'Items per page (default: 10, max: 50)'
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Feed retrieved successfully
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_models.FeedResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_LikhithMar14_gopher-chat_internal_utils.StandardResponse'
      security:
      - ApiKeyAuth: []
      summary: Get user feed
      tags:
      - feed
securityDefinitions:
  ApiKeyAuth:
    description: Description for the API Key
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
